name: 'Zigbee Switch Mc (Add Mode by HanK)'
packageKey: 'Zigbee_Switch_v6.5 - custom HanK'
description: 'Devices: https://github.com/hkm077/Edge-Drivers-Beta/edit/main/zigbee-switch-v6.5/fingerprints.yml'
permissions:
  zigbee: {}
